### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by Thanh-Binh** [marty1885/rps-htm-vs-nn#1]
I have got errors with undefined xt::argmax()  like:
./main.cpp: In function ‘int main()’:
./main.cpp:214:22: error: ‘argmax’ is not a member of ‘xt’
   int rnn_pred = xt::argmax(rnn_out)[0];
                      ^~~~~~
./main.cpp:214:22: note: suggested alternative: ‘amax’
   int rnn_pred = xt::argmax(rnn_out)[0];
                      ^~~~~~
                      amax
./main.cpp:218:22: error: ‘argmax’ is not a member of ‘xt’
   int htm_pred = xt::argmax(htm_out)[0];
                      ^~~~~~
./main.cpp:218:22: note: suggested alternative: ‘amax’
   int htm_pred = xt::argmax(htm_out)[0];

Could you please provide util-function? Thanks

**Comment by marty1885** [comment]
It might be an issue with a old version of xtensor (I have manually updated the xtensor included in tin-dnn).
Please try the latest master.

**Comment by Thanh-Binh** [comment]
Did you try to Compile it? It is not compilable because the file „xsort.hpp“ does not exist in the tiny-dnn repository. It is very kind of you to make sure that your codes are compilable and runable?

**Comment by marty1885** [comment]
Yes I have verified that the patch works on my system before commiting. 
I have pushed a new patch. It should work this time.

**Comment by Thanh-Binh** [comment]
It works now for me. But why did not you train HTM with pattern of sequences? I hope that HTM will perform better than LSTM. I try with „gru“  but it did not work

**Comment by Thanh-Binh** [comment]
It is different to understand that GRU performance is the same like HTM. In my experiment, both have 34%

**Comment by marty1885** [comment]
Hmm weird. In my case I found that LSTM and GRU are performing worse than HTM (Only a few percent). But I believe a winning rate around 33.3% is expected. The outcome becomes a total randomness since both agent are predicting effetely.

BTW. I'm closing the issue. Let's discuss over at HTM Forums.
